function loadFooter(){
  document.write(
  "<div class='footer_intro'>",
  "    <p><span class='myName'>김선우 입니다.</span>",
  "    <br>자동차 인포테인먼트 User Interface/시나리오 디자인 @현대모비스</p>",
  "  </div>",
  "  <div class='footer_content_wrapper'>",
  "    <div class='footer_nav'>",
  "      <div class='footer_title'>NAVIGATION</div>",
  "      <div class='footer_menu_wrapper'>",
  "          <div class='footer_menu'><a href='./Home_kr.html'>HOME</a></div>",
  "          <div class='footer_menu'><a href='./About_kr.html'>ABOUT</a></div>",
  "          <div class='footer_menu'><a href='./Projects_kr.html'>PROJECTS</a></div>",
  "          <div class='footer_menu'><a href='./Works_kr.html'>WORKS</a></div>",
  "          <div class='footer_menu'><a href='./Blog_kr.html'>BLOG</a></div>",
  "          <div class='footer_menu'><a href='./Lecture_kr.html'>LECTURE</a></div>",
  "          <div class='footer_menu'><a href='./Contact_kr.html'>CONTACT</a></div>",
  "      </div>",
  "    </div>",

  "    <div class='footer_contact'>",
  "     <div class='footer_title'>CONTACTS</div>",
  "      <div class='footer_contact_wrapper'>",
  "          <div class='footer_mail'>",
  "            <div class='footer_icon'><i class='far fa-envelope'></i></div>",
  "            <div class='footer_contact_detail'><a href='mailto:anitooni@gmail.com'>anitooni@gmail.com</a></div>",
  "          </div>",
  "          <div class='footer_loc'>",
  "            <div class='footer_icon'><i class='fas fa-map-marker-alt'></i></div>",
  "            <div class='footer_contact_detail'>대한민국, 서울</div>",
  "          </div>",
  "      </div>",
  "    </div>",

  "    <div class='footer_follow'>",
  "      <div class='footer_title'>FOLLOW ME</div>",
  "      <div class='footer_follow_wrapper'>",
  "        <a href= 'https://www.facebook.com/anitooni' target='_blank'>",
  "          <div class='social_icon'><i class='fab fa-facebook-f'></i>",
  "          </div>",
  "          </a>",

  "          <a href= 'https://www.instagram.com/anitooni/' target='_blank'>",
  "          <div class='social_icon'><i class='fab fa-instagram'></i></div>",
  "          </a>",

  "          <a href= 'https://www.linkedin.com/in/sunwoo-kim-7853a83b/' target='_blank'>",
  "          <div class='social_icon'><i class='fab fa-linkedin-in'></i></div>",
  "          </a>",

  "          <a href= 'https://medium.com/@anitooni' target='_blank'>",
  "          <div class='social_icon'><i class='fab fa-medium-m'></i></div>",
  "          </a>",

  "          <a href= 'https://brunch.co.kr/@anitooni#articles' target='_blank'>",
  "          <div class='social_icon'><img src='./images/brunch.png'></img></div>",
  "          </a>",
  "      </div>",
  "    </div>",
  "</div>",
  "<div class='footer_outro'>",
  "  <p>Copyright 2019 | Sunwoo Kim | 즐겁게 보셨나요? 방문해 주셔서 감사합니다.</p>",
  "</div>"
  );
};
