function loadFooter(){
  document.write(
  "<div class='footer_intro'>",
  "    <p><span class='myName'>Sunwoo Kim</span>",
  "    <br>In vehicle HMI DESIGNER & ARCHITECT at HYUNDAI MOBIS</p>",
  "  </div>",
  "  <div class='footer_content_wrapper'>",
  "    <div class='footer_nav'>",
  "      <div class='footer_title'>NAVIGATION</div>",
  "      <div class='footer_menu_wrapper'>",
  "          <div class='footer_menu'><a href='./index.html'>HOME</a></div>",
  "          <div class='footer_menu'><a href='./About.html'>ABOUT</a></div>",
  "          <div class='footer_menu'><a href='./Projects.html'>PROJECTS</a></div>",
  "          <div class='footer_menu'><a href='./Works.html'>WORKS</a></div>",
  "          <div class='footer_menu'><a href='./Blog.html'>BLOG</a></div>",
  "          <div class='footer_menu'><a href='./Lecture.html'>LECTURE</a></div>",
  "          <div class='footer_menu'><a href='./Contact.html'>CONTACT</a></div>",
  "      </div>",
  "    </div>",

  "    <div class='footer_contact'>",
  "     <div class='footer_title'>CONTACTS</div>",
  "      <div class='footer_contact_wrapper'>",
  "          <div class='footer_mail'>",
  "            <div class='footer_icon'><i class='far fa-envelope'></i></div>",
  "            <div class='footer_contact_detail'><a href='mailto:anitooni@gmail.com'>anitooni@gmail.com</a></div>",
  "          </div>",
  "          <div class='footer_loc'>",
  "            <div class='footer_icon'><i class='fas fa-map-marker-alt'></i></div>",
  "            <div class='footer_contact_detail'>Seoul, South Korea</div>",
  "          </div>",
  "      </div>",
  "    </div>",

  "    <div class='footer_follow'>",
  "      <div class='footer_title'>FOLLOW ME</div>",
  "      <div class='footer_follow_wrapper'>",
  "        <a href= 'https://www.facebook.com/anitooni' target='_blank'>",
  "          <div class='social_icon'><i class='fab fa-facebook-f'></i>",
  "          </div>",
  "          </a>",

  "          <a href= 'https://www.instagram.com/anitooni/' target='_blank'>",
  "          <div class='social_icon'><i class='fab fa-instagram'></i></div>",
  "          </a>",

  "          <a href= 'https://www.linkedin.com/in/sunwoo-kim-7853a83b/' target='_blank'>",
  "          <div class='social_icon'><i class='fab fa-linkedin-in'></i></div>",
  "          </a>",

  "          <a href= 'https://medium.com/@anitooni' target='_blank'>",
  "          <div class='social_icon'><i class='fab fa-medium-m'></i></div>",
  "          </a>",

  "          <a href= 'https://brunch.co.kr/@anitooni' target='_blank'>",
  "          <div class='social_icon'><img src='./images/brunch.png'></img></div>",
  "          </a>",
  "      </div>",
  "    </div>",
  "</div>",
  "<div class='footer_outro'>",
  "  <p>Copylight 2019 | Sunwoo Kim, Thanks to visit.</p>",
  "</div>"
  );
};
